import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Home from "./page";
import Link from "next/link";
import Nav from "../components/Nav";

const inter = Inter({ subsets: ["latin"] });

//
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* title */}
      <head>
        <title>Tami Kim</title>
        {/* will add meta tag */}
      </head>
      <body
        className={`antialiased min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50 ${inter.className}`}
      >
        <div className="max-w-2xl mx-auto py-10 px-4 selection:bg-slate-300">
          <header>
            <div className="flex items-center justify-between">
              {/* mode toggle */}
              <button>mode</button>
              <nav className="ml-auto text-sm font-medium space-x-6">
                <Link href="/">Home</Link>
                <Link href="/about">About</Link>
                <Link href="/post">Post</Link>
              </nav>
            </div>
          </header>

          {/* children will be all the pages */}
          <main className="my-5">{children}</main>
        </div>
      </body>
    </html>
  );
}
